### ISSUE TITLE
Sorting/Ordering on the Products Page

### ISSUE THREAD

**Issue by jonathanhauge** [RainyDayMedia/uskoshin#4]
Is there a quick or easy way to add sorting to this page or allow me to sort it in a particular order?

http://uskoshin.inthera.in/products-and-solutions/

Based on Category?
Allow the user to sort?

Don't know if there is an answer, but figured I'd ask. Rather long list running down the left side.

**Comment by ginfuru** [comment]
It sorts by post date- I can reactor this but it's out of scope. Let me see what I can do, but I will need more hours.

**Comment by jonathanhauge** [comment]
Hi @ginfuru,

Could you provide an idea on how many additional hours may be required for this?

**Comment by jonathanhauge** [comment]
@ginfuru I do not see an Estimate of time on this task and the question posed 22 days ago regarding how many additional hours has not been answered. I checked Slack as you stated that you thought you had provided an answer there as well and I do not see any information regarding it.

Could you please give me some insight?

**Comment by ginfuru** [comment]
Please us waffle. And you'll see the time estimates

**Comment by jonathanhauge** [comment]
Is the "size" the hours? Sorry this is the first day I've had access to Waffle for Koshin.

**Comment by ginfuru** [comment]
@jonathanhauge I crated a new template that lists out the categories.
*As discussed on the phone today:*
- [x] I removed all the nested _(child)_ categories, due to the face that one items was under each.  
- [x] added all posts to correct _Parent_ category
